[project]
name = "quant-agent"
version = "0.1.0"
requires-python = ">=3.10"

[project.dependencies]
pandas = "^2.2"
numpy  = "^1.26"
fastapi = "^0.111"
uvicorn = {extras = ["standard"], version = "^0.29"}
python-dotenv = "^1.0"
pyarrow = "^15.0"                # 如果用 Parquet
